AWSTemplateFormatVersion: "2010-09-09"
Description: Reusable Lambda Function Template

Parameters:
  LambdaFunctionName:
    Type: String
  LambdaS3Key:
    Type: String
  LambdaRoleArn:
    Type: String
  LambdaPermissionSourceArn:
    Type: String

Resources:
  LambdaFunction:
    Type: "AWS::Lambda::Function"
    Properties:
      FunctionName: !Ref LambdaFunctionName
      Runtime: provided.al2023
      Handler: bootstrap
      MemorySize: 128
      Code:
        S3Bucket: "eb-solutions-code-deployment"
        S3Key: !Ref LambdaS3Key
      Role: !Ref LambdaRoleArn
      Timeout: 60
      Tags:
        - Key: CostCenter
          Value: projects.go.apigw-lambda

  LambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !GetAtt LambdaFunction.Arn
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com
      SourceArn: !Ref LambdaPermissionSourceArn

Outputs:
  LambdaArn:
    Value: !GetAtt LambdaFunction.Arn
