Description: API Gateway and lambda
AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  TemplateFolder:
    Type: String
    Default: https://eb-solutions-code-deployment.s3.amazonaws.com/projects/go/apigw-lambda
  S3KeyPath:
    Type: String
  HostedZoneId:
    Type: String
    Description: "Route 53 Hosted Zone ID for the domain"
    Default: "ZR2VAHLVW389H"

Resources:
  ApiGateway:
    Type: "AWS::ApiGateway::RestApi"
    Properties:
      Name: "go-apigw"

  HelloGetLambdaStack:
    DependsOn: [ApiGateway]
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateFolder}/lambda-stack-template.yml"
      Parameters:
        LambdaFunctionName: "go-apigw-hello-get"
        LambdaS3Key: !Sub "projects/go/apigw-lambda/${S3KeyPath}/handler_hello_get.zip"
        LambdaRoleArn: arn:aws:iam::654918520080:role/go-apigw-lambda-role
        LambdaPermissionSourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*

  HelloPostLambdaStack:
    DependsOn: [ApiGateway]
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "${TemplateFolder}/lambda-stack-template.yml"
      Parameters:
        LambdaFunctionName: "go-apigw-hello-post"
        LambdaS3Key: !Sub "projects/go/apigw-lambda/${S3KeyPath}/handler_hello_post.zip"
        LambdaRoleArn: arn:aws:iam::654918520080:role/go-apigw-lambda-role
        LambdaPermissionSourceArn: !Sub arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*

  ApiGatewayResourceStack:
    DependsOn: [ApiGateway]
    Type: "AWS::ApiGateway::Resource"
    Properties:
      RestApiId: !Ref ApiGateway
      ParentId: !GetAtt ApiGateway.RootResourceId
      PathPart: "hello"

  ApiGatewayStackMethodHelloGet:
    DependsOn: [LambdaFunctionHelloGet, ApiGateway, ApiGatewayResourceStack]
    Type: "AWS::ApiGateway::Method"
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref ApiGatewayResourceStack
      AuthorizationType: NONE
      HttpMethod: GET
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloGetLambdaStack.Outputs.LambdaArn}/invocations

  ApiGatewayStackMethodHelloPost:
    DependsOn: [LambdaFunctionHelloPost, ApiGateway, ApiGatewayResourceStack]
    Type: "AWS::ApiGateway::Method"
    Properties:
      RestApiId: !Ref ApiGateway
      ResourceId: !Ref ApiGatewayResourceStack
      AuthorizationType: NONE
      HttpMethod: POST
      Integration:
        IntegrationHttpMethod: POST
        Type: AWS_PROXY
        Uri: !Sub arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${HelloPostLambdaStack.Outputs.LambdaArn}/invocations

  ApiGatewayDeployment:
    DependsOn: [ApiGatewayStackMethodHelloGet, ApiGatewayStackMethodHelloPost]
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref ApiGateway
      StageName: prod

  DomainName:
    Type: "AWS::ApiGateway::DomainName"
    Properties:
      # This is the *.otterandcow.com ACM Cert ARN
      CertificateArn: arn:aws:acm:us-east-1:654918520080:certificate/b4d67bb3-5d56-4d5e-bf83-cdf7cb04d4ba
      DomainName: go.otterandcow.com

  Mapping:
    DependsOn: [ApiGateway, DomainName]
    Type: "AWS::ApiGateway::BasePathMapping"
    Properties:
      DomainName: !Ref DomainName
      RestApiId: !Ref ApiGateway
      Stage: prod

  ApiGwRoute53:
    DependsOn: [DomainName]
    Type: "AWS::Route53::RecordSet"
    Properties:
      HostedZoneId: !Ref HostedZoneId
      Name: go.otterandcow.com.
      Type: A
      AliasTarget:
        HostedZoneId: !GetAtt DomainName.DistributionHostedZoneId
        DNSName: !GetAtt DomainName.DistributionDomainName
